name: MATRIX_DEMO

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version: [12,13,14,15,16,17,18,19]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/node-setup@v3
        with:
          node-version: ${{node-version}}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
