name: MATRIX_DEMO

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version: [16,18]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/node-setup@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
